on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get branch name
        id: branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')" >> $GITHUB_ENV

      - name: Set release version
        id: version
        run: echo "RELEASE_TAG=${BRANCH_NAME}-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ZMK Firmware Build (${{ env.BRANCH_NAME }}) - ${{ env.RELEASE_TAG }}
          body: "Automated build release for branch **${{ env.BRANCH_NAME }}**\n\nCommit: `${{ github.sha }}`"
          draft: false
          prerelease: false
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

